import Head from 'next/head';
import { Inter } from 'next/font/google';

import Image from 'next/image';
import Header from '@components/Header/Header';
import Container from '@components/Container/Container';
import Button from '@components/Button/Button';

import products from '@data/products.json';

import styles from '@styles/Home.module.scss';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='preconnect' href='https://app.snipcart.com' />
        <link rel='preconnect' href='https://cdn.snipcart.com' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />
      <main className={`${styles.main} ${inter.className}`}>
        <Container>
          <h1>Hyper Bros. Trading Cards</h1>
          <h2>Available Cards</h2>
          <ul className={styles.products}>
            {products.map((product) => {
              return (
                <li key={product.id}>
                  <Image
                    width='864'
                    height='1200'
                    layout='intrinsic'
                    src={product.image}
                    alt={`Card of ${product.title} `}
                    className={styles.productImage}
                  />
                  <h3 className={styles.productTitle}>{product.title} 12</h3>
                  <p className={styles.productPrice}>${product.price}</p>
                  <Button>Add to Cart</Button>
                </li>
              );
            })}
          </ul>
        </Container>
      </main>
      <footer className={styles.footer}>
        &copy; My Store, {new Date().getFullYear()}
      </footer>
    </>
  );
}
